---
title: Ampersand | Hugo | Forestry
baseURL: "/"
params:
  layout_style: list
  palette: red
  header:
    title: Ampersand | Hugo | Forestry
    logo_img: ''
    has_nav: true
  footer:
    content: "&copy; Todos os direitos reservados."
    links:
    - text: Made with Stackbit
      url: https://www.stackbit.com
      new_window: true
    has_social: true
disableKinds:
- RSS
- taxonomy
- taxonomyTerm
